security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/speaker/add, roles: ROLE_ADMIN }
        - { path: ^/speaker/delete, roles: ROLE_ADMIN }
        - { path: ^/conference/add, roles: ROLE_ADMIN }
        - { path: ^/conference/delete, roles: ROLE_ADMIN }
        - { path: ^/room/add, roles: ROLE_ADMIN }
        - { path: ^/room/delete, roles: ROLE_ADMIN }
        - { path: ^/session/add, roles: ROLE_ADMIN }
        - { path: ^/session/delete, roles: ROLE_ADMIN }